version: '2.2'

services:

  node:
    build: ./images/node
    command: npm start
    env_file:
      - ./.env_app
    volumes:
      - ./app:/var/www/html
    ports:
      - "${WEBSERVER_PORT}:${APP_PORT}"
    links:
      - postgres

  postgres:
    image: postgres:11.3
    volumes:
      - ./postgres/db:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "${DB_ROOT_USER}"
      POSTGRES_PASSWORD: "${DB_ROOT_PASSWORD}"
      PG_DATA: ./postgres/db
